### PR TITLE
1551: Update homepage-hero image

### PR DESCRIPTION
**Pull request by stevejalim**
This changeset updates the homepage hero image.

* Moved into a mzp-l-content div so that it is restricted in the same way page content is (so has the same margins)

* Extra breakpoints tweaked to improve reflow:
 - small viewport: no image
 - medium viewport: bleeds out both sides of screen
 - large viewport: restricted to overall width of mzp-l-content div

-----
**Large/desktop viewport**

Screenshot 2020-06-11 at 12 35 49
-----
**Medium viewport**

Screenshot 2020-06-11 at 12 35 42
-----
**Mobile viewport**

Screenshot 2020-06-11 at 12 35 31

@1x and @2x versions were generated from supplied image, but needed a little feathering on the right-left side to make the fade out go fully to 0 alpha

Cross-browser tested at @1x and @2x resolutions

## How to test

- Deployed to staging

### CODE REVIEW

**Comment by stevejalim** [comment]
@valgrimm Whatcha think? We could make the image align with the main grid, but thought I'd show it like this first

**Comment by valgrimm** [comment]
Hi Steve, I think this needs to move a little to the left, there's a lot of empty space and it looks cut off.

**Comment by stevejalim** [comment]
Hi @valgrimm  
> a little to the left

Can you be a bit more specific, please? Would you like the hard line at the right of the image to vertically align with the right-hand edge of the content on the page?

ie, this?

Screenshot 2020-06-11 at 09 46 48

**Comment by valgrimm** [comment]
Wow, I was unclear. 

> Can you be a bit more specific, please? Would you like the hard line at the right of the image to 
> vertically align with the right-hand edge of the content on the page?
> ie, this?

Very yes.

**Comment by stevejalim** [comment]
@valgrimm Ready on staging for re-review. Please try it at different browser widths - cheers!

**Comment by valgrimm** [comment]
homepage

Corrected asset

**Comment by stevejalim** [comment]
@valgrimm Ah that's a shame - I'll have to re-retouch the latest image so that it blends fully to white before it reaches the left edge, else it leaves an awkward pale-purple edge. 

Will ping you when it's done

**Comment by stevejalim** [comment]
@valgrimm Updated on staging. Re-approval requested, whenever you have a mo

**Comment by stevejalim** [comment]
Thanks. I'll park this until it's ready to deploy - can you ping me when it's cleared for takeoff, please?

**Comment by valgrimm** [comment]
Will do

**Comment by valgrimm** [comment]
This is cleared for takeoff by Chris.

**Pull request merged**
