### PR TITLE
235: Add and reinstate cron jobs

### PR DESCRIPTION
**Pull request by stevejalim**
This changeset addresses the need to auto-publish the site to S3 regularly, as well as the standard Wagtail need to support scheduled publishing/unpublishing of pages (#235)

Notes/context: 

* While we won't be automatically un-publishing Event pages once they have passed, we may want to auto-publish them when the time is right. 
* Events that are in the past will be accessible via their regular URIs, but they should not appear in lists of upcoming events for more than a day after they have taken place. The code that renders such a list will use Django's `filter()` method to not show them in the site. As such, we need to regularly bake out a new static site to ensure that the static content is as up to date as possible.

## Key changes:

* Add job to trigger scheduled publishing of pages
* Reinstate job to build a new static site and sync it to S3

Note these changes are based closely on what was done before and then removed and those changes came with some comments that sound like there may be a better way (hence this only being a draft PR right now). @escattone - can you clue me in to what you had in mind when you said `"Note-to-self: Modify to use our build script."` re these two adjacent comments, please?

- https://github.com/mdn/developer-portal/pull/29#discussion_r305553372
- https://github.com/mdn/developer-portal/pull/29#discussion_r305553517 

## How to test

- locally, `docker-compose build` to run the setup again:
```
...
Step 12/25 : RUN crontab -l | { cat; echo '0 * * * * /usr/local/bin/python /app/manage.py publish_scheduled_pages'; } | crontab -
 ---> Running in ec2c0ca84d3f
Removing intermediate container ec2c0ca84d3f
 ---> 40e5dbf45472
Step 13/25 : RUN crontab -l | { cat; echo '10 * * * * /usr/local/bin/python /app/manage.py build && /usr/local/bin/python /app/manage.py publish'; } | crontab -
 ---> Running in 5eef8fa87706
Removing intermediate container 5eef8fa87706
...
```

Shell into the container and check the crontab:
```
/app # crontab -l
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly

0 * * * * /usr/local/bin/python /app/manage.py publish_scheduled_pages
10 * * * * /usr/local/bin/python /app/manage.py build && /usr/local/bin/python /app/manage.py publish
/app # 
```

## Thoughts / open questions

* Is there a better way than this?  Happy to change
* If this now runs in local dockers, do we want to add an env-var flag to disable it locally?

### CODE REVIEW

**Comment by stevejalim** [comment]
@escattone - could you chip in on this when you get a mo, please, particularly ?
@limed I'd really appreciate your view, too - is there anything i've overlooked?

**Comment by escattone** [comment]
@stevejalim Added myself as an assignee simply for work-tracking purposes for zenhub

**Comment by escattone** [comment]
@stevejalim Regarding my two comments:

> Note-to-self: For our use case, I need to replace /usr/local/bin/python /app/manage.py build with our build script.

> Note-to-self: Modify to use our build script.


You can completely ignore them! 😄 They were made within the context of the `build` target being a sub-path of the MDN domain (e.g., https://developer.mozilla.org/portal), and in that case I had created a separate (and half-finished) `build-portal` command to handle the non-standard "needs" of that case (see https://github.com/mdn/developer-portal/pull/33 and https://github.com/mdn/developer-portal/pull/88 for history).

**Comment by stevejalim** [comment]
@escattone Thanks for the feedback, and I agree that making it a k8s `CronJob` is better - it's more visible and cleaner (so gets rid of my "we want to stop this running in local docker" issue etc)

@limed Would you be OK to take over this ticket and implement the crons that are specced here, please? Feel free to do it on a separate branch and close this draft PR unmerged. Cheers!

**Comment by limed** [comment]
> @limed Would you be OK to take over this ticket and implement the crons that are specced here, please? Feel free to do it on a separate branch and close this draft PR unmerged. Cheers!

Yup I can deal with the `CronJob` but I believe we should wait for the celery work to be done first?

**Comment by stevejalim** [comment]
@limed This isn't blocking anything, no, so waiting for the Celery branch
to be merged is fine.

Indeed, thinking about it, once we have the Celery branch merged, that is
gonna change the chain of actions, potentially.

I'll write it up in a doc/wiki page so we can all get in the same headspace
about how it should roll. Suggestions will be very welcome!

**Comment by stevejalim** [comment]
@limed See https://github.com/mdn/developer-portal/pull/280 -- got a couple of questions on there that I'd apprecaite your input on

**Comment by stevejalim** [comment]
@limed The spec for the jobs to be run is going to change slightly to use a new management command instead of the ones mentioned in the current diff - see https://github.com/mdn/developer-portal/issues/296

**Comment by stevejalim** [comment]
Closing because this should be done at the k8s level, as per discussion above

**Pull request closed without merging**
