### PR TITLE
1604: Marker for mozilla sponsored events

### PR DESCRIPTION
**Pull request by stevejalim**
This changeset adds a way to mark certain events as 'Sponsored by Mozilla', and shows that in the Events list and on the Event detail

UPDATED: to support a custom label, with a fallback phrase if no one is provided.

(Related issue #1604)

## Screenshots
Screenshot 2020-07-01 at 14 11 51

Screenshot 2020-07-01 at 14 17 32

Screenshot 2020-07-01 at 14 17 40

Screenshot 2020-07-01 at 14 17 44

Screenshot 2020-07-01 at 14 29 24

Screenshot 2020-07-01 at 15 49 12

Screenshot 2020-07-01 at 15 49 24

## Key changes:

* Adds a BooleanField to mark if an Event was backed by Mozilla
* Adds a CharField (optional) to allow describing how the event was backed by Mozilla
* Adds a label atom for showing this message
* Use label atom on the Events listing page, in the relevant event-card components
* Use the label on the Event detail page itself by pre-rendering the relevant HTML and passing it into the header strip as a marked-safe HTML string

## How to test

- Code is deployed to stage. 
- Mark some Events as sponsored and confirm that the events listing shows it, as well as the event detail
- Try out the custom label option, too
- Confirm that non-sponsored events don't show the sponsored label in the detail view or the events listing

### CODE REVIEW

**Comment by stevejalim** [comment]
- [ ] @stevejalim Deal with additional requirement reported on the ticket, not the PR: https://github.com/mdn/developer-portal/issues/1604#issuecomment-652284249

**Comment by stevejalim** [comment]
@Gregoor @valgrimm Ready for re-review following additions

**Comment by stevejalim** [comment]
@valgrimm How do the labels look on Win 10 in Edge, if you have it locally? On Browserstack the labels look a bit blurry, but what about on a physical device?

**Comment by valgrimm** [comment]
Checked on Edge on Windows 10, looks crisp.

**Pull request merged**
