### PR TITLE
Reverting c594f31c999088f28a2caf66730915f852428cab

### PR DESCRIPTION
**Pull request by limed**

### CODE REVIEW

**Comment by limed** [comment]
Revert of commit c594f31c999088f28a2caf66730915f852428cab

**Comment by limed** [comment]
r=limed

**Comment by stevejalim** [comment]
Heya @limed! Could you clue me in about why this was reverted, please? Looks like it makes sense to have that SSL redirect in place -- is the revert because there's a different/better point in the stack where this is applied instead?

Cheers,
Steve

**Comment by limed** [comment]
> Heya @limed! Could you clue me in about why this was reverted, please? Looks like it makes sense to have that SSL redirect in place -- is the revert because there's a different/better point in the stack where this is applied instead?
> 
> Cheers,
> Steve

Hey @stevejalim I believe when I initially deployed that it caused a redirect loop which is why I took that out. However I would love to actually have auto redirect to SSL enabled without the redirect loop. If you know of a way I am happy to make that happen

**Pull request merged**
