### PR TITLE
XML typo in pattern.html SVG

### PR DESCRIPTION
**Pull request by jasoncartwright**
https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeveloper.mozilla.com%2F

## Key changes:

Remove typo in SVG XML

## How to test

Revalidate HTML

### CODE REVIEW

**Comment by stevejalim** [comment]
@jasoncartwright If you ping me when this is ready for review, I'll get around to it (off today, but can get to a laptop). then I'll push all the changes to prod when they're ready

**Comment by jasoncartwright** [comment]
@stevejalim Nice one. Very minor fix here, it's ready!

**Comment by stevejalim** [comment]
@jasoncartwright Thanks for the ping. Will merge, test and promote to prod later today. Any other tweaks inbound, or just this + the `rel` one already merged?

**Comment by jasoncartwright** [comment]
Thanks! Just picking off some easy fixes from HTML validation failures. Will make issues for any I can't fix.

**Comment by stevejalim** [comment]
@jasoncartwright Aw, you're a gent. I'll get what I've merged shipped out to production now(ish) to reduce the noise

**Pull request merged**
